platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

install! 'cocoapods', :deterministic_uuids => false

# Temporarily comment out podhelper require to allow workflow to generate missing files
# require File.expand_path(File.join('..', 'Flutter', 'podhelper'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Comment out plugin install for now
  # install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))

  # Post-install processing for permission_handler
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'permission_handler_apple'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)', 'PERMISSION_PUSH=1'
          ]
        end
      end
    end
  end
end