name: Flutter iOS Setup

on:
  workflow_dispatch:

jobs:
  setup-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
      - name: Generate iOS files
        run: flutter create .
      - name: Upload ios folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-folder
          path: ios/